export const GET_USERS_FETCH = 'GET_USERS_FETCH';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_VALUE_SUCCESS = 'SET_SEARCH_VALUE_SUCCESS';

export const GET_POSTS_FETCH = 'GET_POSTS_FETCH';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

export const SET_CREATE_POST_UI = 'SET_CREATE_POST_UI';

export const DELETE_POST_FETCH = 'DELETE_POST_FETCH';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const UPDATE_POST_FETCH = 'UPDATE_POST_FETCH';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';

export const CREATE_POST_FETCH = 'CREATE_POST_FETCH';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const TOGGLE_DARKMODE = 'TOGGLE_DARKMODE';
export const TOGGLE_DARKMODE_SUCCESS = 'TOGGLE_DARKMODE_SUCCESS';

export const SET_LOADING_VALUE = 'SET_LOADING_VALUE';

